services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
      DATABASE_URL: mysql+mysqlconnector://fastapi:QWERTYY12345@fastapi-db/fastapi
    ports:
      - '8000:8000'
    restart: "no"
    volumes:
      - ./app:/app
    networks:
      - default
      - testing_api

networks:
  default:
    name: esercitazione-esame-finale_default
  testing_api:
    name: external_bridge
    external: true